In [1]:
#nested if for voter eligibility checker:
age=float(input("Enter your age : "))
if age<0:
    print("Invalid age")
elif age>0 and age<18:
    if age>=0 and age<2:
        print("Hey baby!")
        print("You're not yet eligible to vote")
    elif age>=2 and age<6:
        print("Hey toddler!")
        print("You're not yet eligible to vote")
    elif age>=6 and age<12:
        print("Hey kid!")
        print("You're not yet eligible to vote")
    elif age>=12 and age<18:
        print("Hey Teenager!")
        print("You're not yet eligible to vote")
elif age>=18 and age<111:
    print("hello voter!")
    print("Please cast your vote")
else:
    print("woah, how come you are still alive?")

Enter your age : 20
hello voter!
Please cast your vote


In [2]:
#example of for loop in list 
num=[1,2,3,45,6,7,89]
sum_=0
for i in num:
    sum_=sum_+i**2
print("the sum of squares is : ", sum_)

the sum of squares is :  10045


In [1]:
#string iteration
str_=input("Enter your name ")
for i in str_:
    print (i)  

Enter your name ZIANNA
Z
I
A
N
N
A


In [2]:
#for loop
for i in range(1,11):
    if i==6:
        continue
    else:
        print(i)

1
2
3
4
5
7
8
9
10


In [3]:
#built-in function(bif)
# maximum (max) & minimum (min) function
names=("anya","rihana","rihaan","ziana")
ages=(21,19,23,17)
print(max(names))
print(max(ages))
print(min(names))
print(min(ages))

ziana
23
anya
17


In [4]:
#built-in functions(bif)
#absolute(abs) function
neg=-6.7
print(abs(neg))

6.7


In [5]:
#built-in functions(bif)
#power function
print(pow(3,4)) #3 power 4
print(pow(2,4,5)) #2 power 4 modulus 5

81
1


In [6]:
#built-in functions
#create and access class
class Person:
    name="Singhal"
    age=20
    country="India"
    state= "Punjab"
    grades=[7.8,8.1,8.9,8.3,7.5]
print(dir(Person)) #properties of class
print(Person.name)
print(type(Person.grades))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'age', 'country', 'grades', 'name', 'state']
Singhal
<class 'list'>


In [7]:
#built-in function 
#sum,round,len function
a=[1.2,3.4,5.6,7.8,9.10]
print("The sum of the list is ",sum(a),".")
print("The length of the list is ",len(a),".")
print("_________________________________")
for i in a:
    print("< The round of value of ",i," is ",round(i),">")

The sum of the list is  27.1 .
The length of the list is  5 .
_________________________________
< The round of value of  1.2  is  1 >
< The round of value of  3.4  is  3 >
< The round of value of  5.6  is  6 >
< The round of value of  7.8  is  8 >
< The round of value of  9.1  is  9 >


In [8]:
#user-defined function
# creating a function to find average or mean
def avg(l):
    avg=sum(l)/len(l)
    return avg
our_ages=[19,20,19,20,19,20,19]
print("The average(actual value) of MADMIND gang age is : ",avg(our_ages))
print("The average(round-of value) of MADMIND gang age is : ",round(avg(our_ages)))

The average(actual value) of MADMIND gang age is :  19.428571428571427
The average(round-of value) of MADMIND gang age is :  19


In [9]:
#call by reference
def square(my_list):
    "This function will find the square of items in list"
    squares=[]
    for i in my_list:
        squares.append(i**2)
    return squares
list_=[45,52,13];
result=square(list_)
print("squares of the list is: ", result)

squares of the list is:  [2025, 2704, 169]


In [10]:
#call by value
a="hi"
print(a)

hi


In [11]:
#lambda function
lambda_=lambda argument1, argument2: argument1 + argument2;
m=int(input("Enter the 1st value: "))
n=int(input("Enter the 2nd value: "))
print("The total value is ",lambda_(m,n))

Enter the 1st value: 87
Enter the 2nd value: 79
The total value is  166


In [12]:
#numpy
import numpy as np

#why numpy over list:

#list
plist=[i for i in range(1000)]
start_time=process_time()
plist=[i+5 for i in range(1000)]
end_time=process_time()
print("the time taken by list is: ",end_time - start_time)

#numpy
plist=np.array([i for i in range(1000)])
start_time=process_time()
plist += 5
end_time=process_time()
print("the time taken by numpy is: ",end_time - start_time)

NameError: name 'process_time' is not defined

In [13]:
#np arrays

#1d array
a=np.array([1,2,3,4,5])
print(a.shape)

#2d array
b=np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b.shape)

#3d array
c=np.array([(1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15)])
print(c.shape)

(5,)
(2, 5)
(3, 5)


In [14]:
#create matrix 

x=np.zeros((4,5)) #zero matrix
print(x)
print("_________________")
y=np.ones((3,4)) #ones matrix
print(y)
print("_________________")
z=np.full((2,3),6) # same element matrix
print(z)
print("_________________")
v=np.eye(5)#identical matrix
print(v)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
_________________
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
_________________
[[6 6 6]
 [6 6 6]]
_________________
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
